/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeList: typeof import('./src/components/ChangeList.vue')['default']
    CheckboxFilter: typeof import('./src/components/CheckboxFilter.vue')['default']
    CleanupInfo: typeof import('./src/components/CleanupInfo.vue')['default']
    DebugMenu: typeof import('./src/components/DebugMenu.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElapsedTime: typeof import('./src/components/ElapsedTime.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    OrderChange: typeof import('./src/components/OrderChange.vue')['default']
    OrderChangePrint: typeof import('./src/components/OrderChangePrint.vue')['default']
    OrderLine: typeof import('./src/components/OrderLine.vue')['default']
    OrderLineAttributes: typeof import('./src/components/OrderLineAttributes.vue')['default']
    OrderLineTimeline: typeof import('./src/components/OrderLineTimeline.vue')['default']
    OrderStatus: typeof import('./src/components/OrderStatus.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    PrinterMenu: typeof import('./src/components/PrinterMenu.vue')['default']
    ProductStock: typeof import('./src/components/ProductStock.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SettingsOption: typeof import('./src/components/SettingsOption.vue')['default']
  }
}
