from . import radio_program
from . import radio_schedule_mixin
from . import radio_material
from . import radio_emission
from . import product_template
from . import res_partner
from . import res_company
from . import res_config_settings
from . import sale_subscription
from . import sale_order
from . import account_move
from . import radio_demo
