from . import res_company
from . import res_config_settings
from . import res_partner
from . import product_template
from . import travel_cancellation_policy
from . import travel_trip
from . import travel_activity
from . import travel_group
from . import travel_passenger
from . import sale_order
from . import account_move
from . import crm_lead
from . import travel_demo
