{
    "name": "POS Print Receipt Before Pay ",
    "category": "Point of Sale",
    "summary": """POS Print Receipt Before Pay Print Receipt Before Payment pos prepayment receipt POS Quick Receipt POS Presale Receipt POS Receipt Preview POS Quick Print Receipt Point Of Sale Quick Print Receipt POS Quick Print Receipt,POS Order Quick Print Receipt,Point Of Sale Order Quick Print Receipt,POS Print Receipt Directly, Point Of Sale Direct Receipt,POS Receipt Print,Point Of Sale Direct Receipt,POS Direct Receipt Odoo""",
    "description": """The module introduces a new feature in Odoo Point of Sale (POS) that allows users to preview and print a receipt before payment is made. This functionality is particularly useful in retail and hospitality environments where customers often request to see their bill before finalizing the transaction.""",
    "license": "OPL-1",
    'version': '18.0',
    "depends": ["point_of_sale"],
    "application": True,
    "data": ["views/res_config.xml"],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_receipt_before_pay/static/src/overrides/app/store/pos_store.js",
            "pos_receipt_before_pay/static/src/overrides/screens/order_receipt/order_receipt.xml",
            "pos_receipt_before_pay/static/src/overrides/screens/product_screen/product_screen.xml",
            "pos_receipt_before_pay/static/src/overrides/screens/product_screen/product_screen.js",
            "pos_receipt_before_pay/static/src/overrides/screens/custom_popup/custom_popup.js",
            "pos_receipt_before_pay/static/src/overrides/screens/custom_popup/custom_popup.xml",
        ],
    },
    'author': 'Khaled Hassan',
    'website': "https://apps.odoo.com/apps/modules/browse?search=Khaled+hassan",
    'license': 'OPL-1',
    'images': ['static/description/main_screenshot.png'],
    'price': 21,
    'currency': 'USD',
    'installable': True,
    'application': False,
    'auto_install': False
}
